### ISSUE TITLE
Treat yourself to some bug squashing!

### ISSUE THREAD

**Issue by felliott** [jjn1056/Test-DBIx-Class#30]
Hey John,

I found six open bugs in the TDBIC RT queue that have been fixed and released but not closed.  With a few quick clicks can cut your bug count in half! :)  The issues are:

    https://rt.cpan.org/Public/Bug/Display.html?id=90964
      New Moose may break your code
      closed by: 761bdc6afc

    https://rt.cpan.org/Public/Bug/Display.html?id=97844
      Per-source generated routines cache the resultset
      closed by: 79c8ac41b9

    https://rt.cpan.org/Public/Bug/Display.html?id=85593
      Missing dependency
      closed by: 539513bad9

    https://rt.cpan.org/Public/Bug/Display.html?id=76041
      Bareword "test_recursive" not allowed while "strict subs"
      closed by: eb7425b5d6

    https://rt.cpan.org/Public/Bug/Display.html?id=71056
      Testmysqld trait with connect_info, Test::mysql constructor fails silently
      closed by: 3244ffe247

    https://rt.cpan.org/Public/Bug/Display.html?id=66772
      reset_schema attempts to drop virtual views
      closed by: 396166e58

Cheers,
Fitz

**Comment by colinnewell** [comment]
Thanks for that.  I've cleaned up the bugs.  The only one I left open was [#71056](https://rt.cpan.org/Public/Bug/Display.html?id=71056) as that looked like it might want a little more attention to the error handling.
