### ISSUE TITLE
SchemaManager clean doesn't work if custom sources was provided via deploy_opts

### ISSUE THREAD

**Issue by jacobk** [jjn1056/Test-DBIx-Class#36]
When providing only a subset of a schema sources using:
```perl
deploy_opts => {
    source => ['Table A', ...],
}
```
`reset_schema`, `reset_schema` breaks since it tries to drop all tables even though they were not deployed.

**Comment by VadimPushtaev** [comment]
I can reproduce this (but you mean `sources`, not `source`).

**Comment by colinnewell** [comment]
I've just rolled a release but if you provide a fix I'll be happy to do another.  Alternatively if you can provide a test case I should be able to fix it.  I'm afraid I couldn't figure out how to reproduce that one.

**Comment by VadimPushtaev** [comment]
You just do the following to reproduce:

```perl
diff --git a/t/06-basic-test-schema.t b/t/06-basic-test-schema.t
index 079f27e..b8a0415 100644
--- a/t/06-basic-test-schema.t
+++ b/t/06-basic-test-schema.t
@@ -3,6 +3,7 @@ use warnings;

 use Test::More;
 use Test::DBIx::Class
+    {deploy_opts => {sources => ['Person']}},
     'CD',
     'Person',
     'Person' => {search => {age=>{'>'=>18}}, -as => 'NotTeenager'},
```

I believe the only way to know what sources were actually deployed is analyzing `deploy_opts` (that doesn't look great, but we have no other choice as far as I understand).

**Comment by VadimPushtaev** [comment]
Fixed: https://github.com/jjn1056/Test-DBIx-Class/pull/39

**Comment by colinnewell** [comment]
This has been fixed by @VadimPushtaev and a new release is on it's way to CPAN.
